# loading or creating of data


In [89]:
import numpy as np
studentmarks=np.array([[55,60,70],
[80,60,70],
[80,70,60]],dtype=int)
print(studentmarks.dtype)


int64


In [90]:
np.save("studentmarks.npy",studentmarks)

In [91]:
loading=np.load("studentmarks.npy")
print(loading)

[[55 60 70]
 [80 60 70]
 [80 70 60]]


In [92]:
sumsubjects=np.sum(loading,axis=0)
print(sumsubjects)
print(sumsubjects[0] ," frist subject total")
print(sumsubjects[1] ," second subject total")
print(sumsubjects[2] ," thrid subject total")


#toating as per the students marks row vise
studentper=np.sum(loading,axis=1)
print(studentper)
print(studentper[0], "student number one")
print(studentper[1], "student number two")
print(studentper[2], "student number three")

[215 190 200]
215  frist subject total
190  second subject total
200  thrid subject total
[185 210 210]
185 student number one
210 student number two
210 student number three


#trying to get the avg and top among the student of three

In [93]:
avgstudentscore=np.average(studentper)
print(avgstudentscore)

201.66666666666666


min and max amoung the studets

In [94]:
minmarks=np.min(loading,axis=1)
print(minmarks)
maxsocre=np.max(loading,axis=1)
print(maxsocre)

[55 60 60]
[70 80 80]


# lets try to lad csv file and give a visual reperstion


In [ ]:
load=