In [1]:
import numpy as np
print(np.__version__)

2.1.3


# array in numpy

In [2]:
import numpy as np
arr=np.array([1,2,3,4])
print(type(arr), arr)

<class 'numpy.ndarray'> [1 2 3 4]


## using range to  genarate the array

In [3]:
import numpy as np
#a=np.arange(10)
#a=np.arange(2,10,dtype=float)
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# genarating random  numbers

In [4]:
import numpy as np
from numpy.random import default_rng
b=default_rng(42).random((2,3))
print(b)

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]


In [5]:
a=np.arange(1,45)
print(a)
print(a[3]) #here we passing index value to get the value or element from the array
b=a.searchsorted(8) #here we will handel direct val;ues not index
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
4
7


In [6]:
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [7]:

c=np.arange(1,10,2)
d=np.array([1,5,48,71,89])
e=np.concatenate((c,d))
print(e)
f=np.sort(e)
print(f)
g=np.shape(f)
l=np.size(f)
print(l)
print(g)


[ 1  3  5  7  9  1  5 48 71 89]
[ 1  1  3  5  5  7  9 48 71 89]
10
(10,)


# reshaping the  array

In [8]:
import numpy as np
array=np.arange(6)
array=array.reshape(2,3)
print(array)

##

arr=np.reshape(array,shape=(2,3),order='A')
print(arr)



[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]


# operations like add, sub, multiplation 

In [9]:
a=np.array([1,2])
a1=np.ones(2,dtype=int)
print(a+a1)

[2 3]
